apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-group2-svc-np
spec:
  type: NodePort
  ports:
    - port: 8080
      #targetPort: 80
      nodePort: 30000 # 30000 - 32767
  selector:
    app: tech-challenge-group2